# Generated by Django 3.1.2 on 2020-10-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('manager_name', models.CharField(default='', max_length=100, verbose_name='管理员姓名')),
                ('name', models.CharField(default='', max_length=100, verbose_name='姓名')),
                ('stu_id', models.CharField(default='', max_length=20, verbose_name='学号')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
    ]
