# Generated by Django 3.1.2 on 2020-10-04 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemindModel',
            new_name='RecordModel',
        ),
        migrations.AlterModelOptions(
            name='recordmodel',
            options={'ordering': ['-time'], 'verbose_name': '记录', 'verbose_name_plural': '记录'},
        ),
        migrations.AlterModelTable(
            name='recordmodel',
            table='record',
        ),
    ]
